### ISSUE TITLE
Mistake in cylindrical cell volume calculation? 

### ISSUE THREAD

**Issue by environmat** [mjlacey/cellmodels#1]
Hi, 
quick question, in line 581 / 582 of cellmodel.ji you calculate the cylinder volume of the housing. I was wondering if the second line was correct. 

The original: 
 canvol = (((π * (cell.diameter/2)^2) - (π * (cell.diameter/2 - cell.canthickness)^2)) * cell.height) +
        (**_2π_** * (cell.diameter/2)^2 * cell.canthickness)

Shouldn't it be rather: 
 canvol = (((π * (cell.diameter/2)^2) - (π * (cell.diameter/2 - cell.canthickness)^2)) * cell.height) +
        (**_π_** * (cell.diameter/2)^2 * cell.canthickness)

Thanks already for the great tool! 

Cheers, 
Matthias

**Comment by ndrewwang** [comment]
I believe here he's calculating the literal can volume which is the surface area * steel can thickness : used to work out the mass via density of the can component itself

**Comment by mjlacey** [comment]
Hi @environmat, @ndrewwang is correct with what I'm attempting to do, and I think there might be a mistake in here but maybe a different one. The intention is that the first row is the volume of the walls of the can with both top and bottom open (π(r_outer)^2*h - π(r_inner)^2*h) and then the second row is the top and bottom of the cylinder, so πr^2 * thickness, times 2 for both top and bottom, hence the 2π. But i think the mistake might be that i haven't subtracted the can thickness from the radius in the second line, which means I am double counting the corners. So I think the second line should really be:

(2π * (cell.diameter/2 - cell.canthickness)^2 * cell.canthickness)

Does that make sense and look ok? Thinking about it again I have probably overcomplicated this and would be less confusing to just subtract the volume of one cylinder (space in the empty can) from another cylinder (the can itself)

**Comment by environmat** [comment]
Hi @mjlacey and @ndrewwang, 
thanks for your quick feedback and the explanation. 

Indeed, as I see it, your second line should be correct now, if you substract the canthickness from the diameter.
